development:
  adapter: postgresql
  database: eSorochkaDev
  encoding: unicode
  pool: 16
  username: su
  password: su
  host: localhost

test: &TEST
  adapter: postgresql
  database: eSorochkaTest
  encoding: unicode
  pool: 16
  username: su
  password: su
  host: localhost

production:
  adapter: postgresql
  database: eSorochka
  pool: 16
  encoding: unicode
  username: su
  password: su
  host: localhost

cucumber:
  <<: *TEST
